- name: Pecan Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/pecanpie/pecanpie1.png
    - /assets/images/products/pecanpie/pecanpie2.png
  slug: pecan-pie

- name: Chocolate Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/chocopie/chocopie1.png
    - /assets/images/products/chocopie/chocopie2.png
  slug: choco-pie

- name: Pumpkin Streusel Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/pspie/pspie1.png
    - /assets/images/products/pspie/pspie2.png
  slug: ps-pie

- name: Dutch Apple Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/dapie/dapie1.png
    - /assets/images/products/dapie/dapie2.png
    - /assets/images/products/dapie/dapie3.png
  slug: da-pie

- name: Pumpkin Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/pumpkinpie/pumpkinpie1.png
    - /assets/images/products/pumpkinpie/pumpkinpie2.png
  slug: p-pie

- name: Strawberry Truffle
  price: 34
  category: truffles
  images:
    - /assets/images/products/strawberrytruffle/strawberrytruffle1.jpg
    - /assets/images/products/strawberrytruffle/strawberrytruffle2.jpg
    - /assets/images/products/strawberrytruffle/strawberrytruffle3.jpg
  slug: strawberry-truffle

- name: Biscoff Truffle
  price: 34
  category: truffles
  images:
    - /assets/images/products/biscofftruffle/biscoff-truffle1.jpg
    - /assets/images/products/biscofftruffle/biscoff-truffle2.jpg
    - /assets/images/products/biscofftruffle/biscoff-truffle3.jpg
  slug: biscoff-truffle

- name: Lemon Truffle
  price: 34
  category: truffles
  images:
    - /assets/images/products/lemon-truffle/lemon-truffle1.jpg
    - /assets/images/products/lemon-truffle/lemon-truffle2.jpg
    - /assets/images/products/lemon-truffle/lemon-truffle3.jpg
  slug: lemon-truffle

- name: Mint Truffle
  price: 34
  category: truffles
  images:
    - /assets/images/products/mint-truffle/mint-truffle1.jpg
    - /assets/images/products/mint-truffle/mint-truffle2.jpg
    - /assets/images/products/mint-truffle/mint-truffle3.jpg
  slug: mint-truffle

- name: Oreo Truffle
  price: 34
  category: truffles
  images:
    - /assets/images/products/oreo-truffle/oreo-truffle1.jpg
    - /assets/images/products/oreo-truffle/oreo-truffle2.jpg
    - /assets/images/products/oreo-truffle/oreo-truffle3.jpg
  slug: oreo-truffle

- name: Peanut Butter Truffle
  price: 34
  category: truffles
  images:
    - /assets/images/products/pb-truffle/pb-truffle1.jpg
    - /assets/images/products/pb-truffle/pb-truffle2.jpg
    - /assets/images/products/pb-truffle/pb-truffle3.jpg
  slug: pb-truffle

- name: Oreo Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/oreo-pie/oreo-pie1.jpg
  slug: oreo-pie

- name: Chocolate Pecan Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/choc-pecan-pie/choc-pecan-pie1.jpg
  slug: choc-pecan-pie

- name: Strawberry White Chocolate Chip Cookie
  price: 20
  category: cookies
  images:
    - /assets/images/products/straw-white-choc-cookie/swcc1.jpg
    - /assets/images/products/straw-white-choc-cookie/swcc2.jpg
    - /assets/images/products/straw-white-choc-cookie/swcc3.jpg
  slug: straw-white-choc-cookie

- name: Snickerdoodle
  price: 20
  category: cookies
  images:
    - /assets/images/products/snickerdoodle/snickerdoodle1.jpg
    - /assets/images/products/snickerdoodle/snickerdoodle2.jpg
  slug: snickerdoodle

- name: S'mores Cookie
  price: 20
  category: cookies
  images:
    - /assets/images/products/smores-cookie/smores-cookie1.jpg
    - /assets/images/products/smores-cookie/smores-cookie2.jpg
  slug: smores-cookie

- name: Pumpkin Spice Cookie
  price: 20
  category: cookies
  images:
    - /assets/images/products/pumpkin-spice-cookie/pspice1.jpg
    - /assets/images/products/pumpkin-spice-cookie/pspice2.jpg
    - /assets/images/products/pumpkin-spice-cookie/pspice3.jpg
  slug: pumpkin-spice-cookie

- name: Pumpkin Spice Blossom
  price: 20
  category: cookies
  images:
    - /assets/images/products/pumpkin-spice-blossom/psb1.jpg
    - /assets/images/products/pumpkin-spice-blossom/psb2.jpg
  slug: pumpkin-spice-blossom

- name: Pumpkin Spice Snickerdoodle
  price: 20
  category: cookies
  images:
    - /assets/images/products/pumpkin-spice-snickerdoodle/pss1.jpg
    - /assets/images/products/pumpkin-spice-snickerdoodle/pss2.jpg
  slug: pumpkin-spice-snickerdoodle

- name: Peanut Butter Cookie
  price: 20
  category: cookies
  images:
    - /assets/images/products/peanut-butter-cookie/pbc1.jpg
  slug: peanut-butter-cookie

- name: Peanut Butter Blossom
  price: 20
  category: cookies
  images:
    - /assets/images/products/peanut-butter-blossom/pbb1.jpg
    - /assets/images/products/peanut-butter-blossom/pbb2.jpg
    - /assets/images/products/peanut-butter-blossom/pbb3.jpg
  slug: peanut-butter-blossom