- name: Chocolate Chip Cookie
  price: 20
  category: cookies
  image: /assets/images/products/choco_chip.png
  slug: choco-chip

- name: Red Velvet Cupcake
  price: 20
  category: cupcakes
  image: /assets/images/products/red_velvet.png
  slug: red-velvet

- name: Salted Caramel Truffle
  price: 20
  category: truffles
  image: /assets/images/products/salted_caramel.png
  slug: sugar-cookie

- name: Sugar Cookie
  price: 20
  category: cookies
  image: /assets/images/products/sugar_cookie.png
  slug: sugar-cookie

- name: Snickerdoodle
  price: 20
  category: cookies
  image: /assets/images/products/snickerdoodle.png
  slug: snickerdoodle

- name: Pecan Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/pecanpie/pecanpie1.png
    - /assets/images/products/pecanpie/pecanpie2.png
  slug: pecan-pie

- name: Chocolate Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/chocopie/chocopie1.png
    - /assets/images/products/chocopie/chocopie2.png
  slug: choco-pie

- name: Pumpkin Streusel Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/pspie/pspie1.png
    - /assets/images/products/pspie/pspie2.png
  slug: ps-pie

- name: Dutch Apple Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/dapie/dapie1.png
    - /assets/images/products/dapie/dapie2.png
    - /assets/images/products/dapie/dapie3.png
  slug: da-pie

- name: Pumpkin Pie
  price: 34
  category: pies
  images:
    - /assets/images/products/pumpkinpie/pumpkinpie1.png
    - /assets/images/products/pumpkinpie/pumpkinpie2.png
  slug: p-pie







